//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Run_Multiple_Apps_GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Run_Multiple_Apps_GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ;@echo off
        ///; rem https://github.com/npocmaka/batch.scripts/edit/master/hybrids/iexpress/bat2exeIEXP.bat
        ///;if &quot;%~2&quot; equ &quot;&quot; (
        ///; echo usage: %~nx0 batFile.bat target.Exe
        ///;)
        ///;set &quot;target.exe=%__cd__%%~2&quot;
        ///;set &quot;batch_file=%~f1&quot;
        ///;set &quot;bat_name=%~nx1&quot;
        ///;set &quot;bat_dir=%~dp1&quot;
        ///
        ///;copy /y &quot;%~f0&quot; &quot;%temp%\2exe.sed&quot; &gt;nul
        ///
        ///;(echo()&gt;&gt;&quot;%temp%\2exe.sed&quot;
        ///;(echo(AppLaunched=cmd.exe /c &quot;%bat_name%&quot;)&gt;&gt;&quot;%temp%\2exe.sed&quot;
        ///;(echo(TargetName=%target.exe%)&gt;&gt;&quot;%temp%\2exe.sed&quot;
        ///;(echo(FILE0=&quot;%bat_name%&quot;)&gt;&gt;&quot;%temp%\2exe.sed&quot;
        ///; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bat2ExeIEXP {
            get {
                return ResourceManager.GetString("Bat2ExeIEXP", resourceCulture);
            }
        }
    }
}
